apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: khizershah11/backend:latest
          ports:
            - containerPort: 5050
          env:
                - name: MONGO_URI
                  value: "mongodb://mongo:27017/mydatabase"
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  selector:
    app: backend
  ports:
    - port: 5050
      targetPort: 5050
  type: NodePort
